# Generated by Django 3.1 on 2021-11-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('heure', models.TimeField()),
                ('numero', models.IntegerField()),
                ('communequartier', models.CharField(max_length=100)),
                ('mootifAge', models.TextField()),
                ('specialisation', models.CharField(choices=[('GENERALISTE', 'GENERALISTE'), ('PEDIATRE', 'PEDIATRE')], max_length=100)),
                ('complement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('photomedicament', models.ImageField(upload_to='photomedicaments')),
                ('Prix', models.IntegerField()),
                ('Description', models.TextField()),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rayon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomrayon', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=50)),
                ('medicament', models.ManyToManyField(related_name='medicaments', to='blog.Medicament')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nompharma', models.CharField(max_length=200)),
                ('imagephrama', models.ImageField(upload_to='logopharma')),
                ('commune', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=14)),
                ('slug', models.CharField(max_length=50)),
                ('rayon', models.ManyToManyField(related_name='rayons', to='blog.Rayon')),
            ],
        ),
    ]
