# Generated by Django 3.1 on 2022-01-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_publicite'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacie',
            name='imageproprietaire',
            field=models.ImageField(default=0, upload_to='PROPRIETAIRE'),
            preserve_default=False,
        ),
    ]
