# Generated by Django 3.1 on 2022-01-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_pharmacie_imageproprietaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='sexe',
            field=models.CharField(choices=[('MASCULIN', 'MASCULIN'), ('FEMININ', 'FEMININ')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
